builtin_interfaces/Time stamp        # 记录时间戳
string host_name                     # 主机名字
float32 cpu_usage                    # CPU使用率 (%)
float32 memory_usage                 # 内存使用率 (%)
uint64 memory_total                  # 内存总大小 (bytes)
uint64 memory_free                   # 剩余内存 (bytes)
uint64 network_sent                   # 网络发送总量 (bytes)
uint64 network_received               # 网络接收总量 (bytes)